### ISSUE TITLE
No longer working.

### ISSUE THREAD

**Issue by aydinowicz** [bombsimon/garmin-seaside#1]
I'm not able to run this project on eclipse. I think it's outdated and needs some sort of update. Thanks.

**Comment by bombsimon** [comment]
Thanks for the report!

I just bought a new Garmin Venu 2 and was planning to get this project running again and support AMOLED screens. I'll see if I can fix this for other devices as well!

**Comment by bombsimon** [comment]
Hey! Just got everything up and running with the latest SDK and opted to use Eclipse this time since the IntelliJ support isn't 100%. I just had to set connectIq as project nature in the settings and got this to build. Would you mind help me with steps to reproduce this? Thanks!

![image](https://user-images.githubusercontent.com/3248948/129446407-0235efca-099c-4b0c-a741-7f183ba304f7.png)

![image](https://user-images.githubusercontent.com/3248948/129446415-193a7fcd-7eef-49f4-a20e-9b4bcd9af7c8.png)

![image](https://user-images.githubusercontent.com/3248948/129446426-7d73f159-77e6-4707-bf9d-991f61fa3b04.png)

**Comment by aydinowicz** [comment]
Hey! I already set connect IQ but still can't run this watch face. I don't
know what's missing. Probably some files in the bin folder.

**Comment by bombsimon** [comment]
The bin folder is just the output where the compiled result will end up, it's empty before compiling for the first time.

Do you get any error message? Do you see anything in the console (if you're using Eclipse)?

**Comment by aydinowicz** [comment]
There's no IQ icon on the project folder. I am attaching screenshots for
your reference.

**Comment by bombsimon** [comment]
That indicates that you do not have set up Eclipse properly for the project. Right click on the root folder and select `Properties`. Navigate to `Project Natures`:
![image](https://user-images.githubusercontent.com/3248948/129485014-3e57243d-a9a1-4284-8edb-e5b6f2b10448.png)

Click `Add`, then OK on the popup and select `connectiq.projectNature`: 
![image](https://user-images.githubusercontent.com/3248948/129485037-c3dd4eff-b848-4123-a8e4-4d589e634b24.png)

Click `Apply and Close`, you should now have the `IQ` icon on the project folder and from there be able to build and run the project.

**Comment by aydinowicz** [comment]
Hi Simon,

It gives this error this time;

*BUILD: ERROR: vivoactive3: ERROR: assembler: extraneous input
***@***.***_871091088' expecting {IntNumber, HexNumber, OctalNumber}*
*BUILD: WARNING: The launcher icon (30x30) isn't compatible with the
specified launcher icon size of the device 'vivoactive3' (40x33). Image
will be scaled to the target size.*
*BUILD: WARNING: Character id '0' will not display due to an
incompatibility with the graphics system.*
*BUILD: Complete*
*Aborting launch due to failed build.*

**Comment by bombsimon** [comment]
Have you tried with the [Visual Studio Code](https://developer.garmin.com/connect-iq/reference-guides/visual-studio-code-extension/) extension that seems to replace the Eclipse one? Works just as well with this one for me.
